server:
  port: 8083

spring:

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  sync:
    auth:
      queue: auth.sync.queue
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never



# Internal service communication through Docker network
user:
  service:
    baseUrl: http://user-service:8081

frontend:
  origin: http://localhost

# Internal token for service-to-service communication
internal:
  token: super-secret-sync

# JWT secret
security:
  jwt:
    secret: VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC

# Disable sync to avoid circular calls
sync:
  enabled: true