server:
  port: 8081

spring:
  sync:
    auth:
      queue: auth.sync.queue
  datasource:
    url: jdbc:postgresql://user-db:5432/users_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

# Internal service communication through Docker network
auth:
  service:
    baseUrl: http://auth-service:8083

# Internal token for service-to-service communication
internal:
  token: super-secret-sync

# JWT secret
security:
  jwt:
    secret: VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC

# Disable sync to avoid circular calls
sync:
  enabled: true